language: node_js
sudo: required
cache:
  directories:
  - node_modules
before_install:
- ". $HOME/.nvm/nvm.sh"
- nvm install stable
- nvm use stable
- if [[ `npm -v` != 5.2* ]]; then npm i -g npm@5.2; fi
- export PATH=$PATH:node_modules/.bin/
install:
- npm install --ignore-scripts
- npm update
- make web
- make deploy-cpo-main
deploy:
- provider: s3
  access_key_id:
    secure: "VJHS2439KMsPL4tNYIWASy3uMvx6XI5L3zaI7FwjF2Q4wTkA8lAggAJPNqIiqurGfwyNgzXanpMeFL7zQ4BpYvta1kbdK4kCdSneEmXO1DJyE10a0lF8DG+bz0K34LOqe+xbJtp9Q6NGXEs+4QTFzysPZDsoJtHT+cc9iQ0qgio6/Z88YpNoXlPeB1scF/WlbSZHSUtxkdvoYi4vroC/mF9b+OgcE/K4ZNMSLWemBZQE/aPX8rzONR/FkwMK9EUa90rInBwWR8osd5oxFFnXsbGX0i8wO4M8kOGNJ22nC5Vw8FOSf3DV5TltJl/iU22M9MAJkZeC0CExxEmHPIjLHbN8dbKMJdhyS1CYzbhDmEntGg7x+gYiPX6eHgnsZXFxBBnOCo9dZ7vwdIcM0jGc9ShsPJrwL2DZA5eETOjEfLnflUi7uNai7sJqCRNPCKB5tc8dz4xXwQgnpsrAHx0ndtfFd4NjOa1/z1M/7/GY+AwceBKOAHUaHz/Pr94LqqomZQe0Zo4vQp9uWUW/fh+LfQW9vzXXhMUQLlZuLq1jVyh53jMyEoIChZMpGjFdGu7ssB8Q6gSM9aR1BHk1azlADJddrvUOZUjrWAwVNnsJTgLf+8h+jcaM3SBgKjDX2pAtfYSyiO//3GJ7lkB1cYdzv1VlO+ChdLVKEXa0xoNwrPI="
  secret_access_key:
    secure: "fjnudjH82YUhprFQzU1WP5zXAQaEqHIWpoO3gEyM9Zp0qNzreyrg6DozfUszjJ1WKQJfzH0Rq7U68e3+otox6x07FV49zdNHh6ndh3bBH/uQjDjZcP69p/abc2q+uwWcyfnChs9t0Yl8Vw828ncYLPN+SryTvevRtBcIiuJLCJOMCy92CVhe0Vj8k1pKRxxWpAOfMWOFMcF4JkUJhm0d8y4OwIT9zYjzwqg0sSR4hIFEwt3WRdXNYLupv3AIuEDWGw+mloNy0Mg3iuRtz7nfeLc9cMOwy5rGu6/E6b3/Tqt+gdbPE/Hpjh2cRVCgHLYUG+Dg0RiqWoz1D6fyl7+nVuFIcEXePBY31aIserbPJh8fls2m/T1KjFB3B1ALuW+Pu6abDIKCOiuQc/0yl76HSaTu/LMGoHe/7SJ6gueisHZtox/qhLVqUO1yEY4Jgj0ILQOAxGJ7kzuH5RKNUUIL8SBOJvD3LZJA9YfZWA0SMCHFO/H1S97V00wpKdlODEhDWRHygWs7IEv0OGL1j2CywRkkqguWnHVwS5CqB5FZWzFx9Igmham8Ik7UHyrwAxPmvkFQHdak7N7lvbVS1N5sBIeGAmC0rjJuB+WesguMZi70ChX+IFeTGKfmal3bN424A9QNSXan31nLr4nPgcLu8EAMQiz+kcuO0eG5ruvKwPk="
  bucket: 'brown-data-druid'
  local-dir: build/web/js
  upload-dir: prompted
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mxheller/code.pyret.org
    branch: repl-hook
- provider: s3
  access_key_id:
    secure: "VJHS2439KMsPL4tNYIWASy3uMvx6XI5L3zaI7FwjF2Q4wTkA8lAggAJPNqIiqurGfwyNgzXanpMeFL7zQ4BpYvta1kbdK4kCdSneEmXO1DJyE10a0lF8DG+bz0K34LOqe+xbJtp9Q6NGXEs+4QTFzysPZDsoJtHT+cc9iQ0qgio6/Z88YpNoXlPeB1scF/WlbSZHSUtxkdvoYi4vroC/mF9b+OgcE/K4ZNMSLWemBZQE/aPX8rzONR/FkwMK9EUa90rInBwWR8osd5oxFFnXsbGX0i8wO4M8kOGNJ22nC5Vw8FOSf3DV5TltJl/iU22M9MAJkZeC0CExxEmHPIjLHbN8dbKMJdhyS1CYzbhDmEntGg7x+gYiPX6eHgnsZXFxBBnOCo9dZ7vwdIcM0jGc9ShsPJrwL2DZA5eETOjEfLnflUi7uNai7sJqCRNPCKB5tc8dz4xXwQgnpsrAHx0ndtfFd4NjOa1/z1M/7/GY+AwceBKOAHUaHz/Pr94LqqomZQe0Zo4vQp9uWUW/fh+LfQW9vzXXhMUQLlZuLq1jVyh53jMyEoIChZMpGjFdGu7ssB8Q6gSM9aR1BHk1azlADJddrvUOZUjrWAwVNnsJTgLf+8h+jcaM3SBgKjDX2pAtfYSyiO//3GJ7lkB1cYdzv1VlO+ChdLVKEXa0xoNwrPI="
  secret_access_key:
    secure: "fjnudjH82YUhprFQzU1WP5zXAQaEqHIWpoO3gEyM9Zp0qNzreyrg6DozfUszjJ1WKQJfzH0Rq7U68e3+otox6x07FV49zdNHh6ndh3bBH/uQjDjZcP69p/abc2q+uwWcyfnChs9t0Yl8Vw828ncYLPN+SryTvevRtBcIiuJLCJOMCy92CVhe0Vj8k1pKRxxWpAOfMWOFMcF4JkUJhm0d8y4OwIT9zYjzwqg0sSR4hIFEwt3WRdXNYLupv3AIuEDWGw+mloNy0Mg3iuRtz7nfeLc9cMOwy5rGu6/E6b3/Tqt+gdbPE/Hpjh2cRVCgHLYUG+Dg0RiqWoz1D6fyl7+nVuFIcEXePBY31aIserbPJh8fls2m/T1KjFB3B1ALuW+Pu6abDIKCOiuQc/0yl76HSaTu/LMGoHe/7SJ6gueisHZtox/qhLVqUO1yEY4Jgj0ILQOAxGJ7kzuH5RKNUUIL8SBOJvD3LZJA9YfZWA0SMCHFO/H1S97V00wpKdlODEhDWRHygWs7IEv0OGL1j2CywRkkqguWnHVwS5CqB5FZWzFx9Igmham8Ik7UHyrwAxPmvkFQHdak7N7lvbVS1N5sBIeGAmC0rjJuB+WesguMZi70ChX+IFeTGKfmal3bN424A9QNSXan31nLr4nPgcLu8EAMQiz+kcuO0eG5ruvKwPk="
  bucket: 'brown-data-druid'
  local-dir: build/web/js
  upload-dir: unprompted
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mxheller/code.pyret.org
    branch: playground